(()=>{
'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const areas=['Usinagem','Retífica','Qualidade','Lavagem','Engenharia','Acabamento Rebarbação','Acabamento Tamboreamento','Sala Limpa','Manutenção','Gravação a Laser','Eletrolise','Controle de Qualidade','Operadores','Preparadores','Programadores','Processos','Pre Set','Montagem','Ferramentaria'];
const roles=[...new Set((window.orthoSeed||[]).map(p=>p.role)),'Liderança','Operador','Auxiliar','Preparador','Programador','Processos','Pre Set','Montagem','Ferramentaria'];
const shifts=['1º turno','2º turno','3º turno','Administrativo'];
let db={people:[],vacations:[],reviews:[],machines:[],support:[],audit:[]},page='Colaboradores',query='',filter='',pageNo=1;
const uuid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
const today=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmt=d=>d?new Date(d.length===10?d+'T12:00:00':d).toLocaleDateString('pt-BR'):'—';
const active=(p,d=today())=>(!p.start||p.start<=d)&&(!p.end||p.end>d);
const person=id=>db.people.find(p=>p.id===id);
const personName=id=>person(id)?.name||'Colaborador removido';
const overlap=(a,b)=>a.start<=b.end&&b.start<=a.end;
const clamp=n=>Math.max(0,Math.min(10,n));
const score=id=>db.reviews.filter(r=>r.person===id).sort((a,b)=>a.date.localeCompare(b.date)||a.created.localeCompare(b.created)).reduce((n,r)=>clamp(n+Number(r.delta)),10);
function audit(action,type,before,after){db.audit.unshift({id:uuid(),date:new Date().toISOString(),user:'U135613 (demonstração)',action,type,before,after});}
function toast(message){$('#notice').textContent=message;$('#notice').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#notice').classList.remove('visible'),3500);}
function download(name,data,type){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function csv(rows){if(!rows.length)return toast('Nenhum registro para exportar.');const keys=Object.keys(rows[0]),cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';download('NeoOrtho_'+page.replaceAll(' ','_')+'.csv','\ufeff'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}

const seed=window.orthoSeed||[];
db.people=seed.map(p=>({...p,id:p.registration,cost:'',start:p.since?p.since.split('/').reverse().join('-'):'',end:'',birth:'',notes:'Exemplo visual do arquivo original.'}));
function syncPeople(){window.syncOrthoCollaborators?.(db.people.map(p=>({...p,initials:p.name.split(/\s+/).filter(Boolean).slice(0,2).map(n=>n[0]).join(''),status:!active(p)||db.vacations.some(v=>v.person===p.id&&v.start<=today()&&v.end>=today())?'ausente':'ativo',manager:p.manager||'U135613',since:fmt(p.start),availability:active(p)?'Em atividade':'Fora do quadro',location:p.area,shiftStart:p.shiftStart||'—',shiftEnd:p.shiftEnd||'—',progress:p.progress||0,updated:'Prévia local'})));}
window.orthoActions={add:()=>{page='Colaboradores';edit('people');},edit:registration=>{page='Colaboradores';const p=db.people.find(p=>p.registration===registration);if(p)edit('people',p.id);},profile:registration=>{page='Colaboradores';const p=db.people.find(p=>p.registration===registration);if(p)profile(p.id);}};
const configs={
'Colaboradores':{key:'people',title:'Sua equipe, de perto.',desc:'Informações, trajetória e desenvolvimento em um só lugar.',add:'Incluir colaborador',fields:[['name','Nome completo','text',true],['registration','Matrícula','text',true],['area','Área',areas,true],['shift','Turno',shifts,true],['role','Cargo',roles,true],['cost','Centro de custo','text',true],['start','Data de entrada','date',true],['end','Data de saída','date'],['birth','Nascimento','date'],['notes','Observações','textarea']],columns:[['name','Colaborador'],['registration','Matrícula'],['area','Área'],['shift','Turno'],['role','Cargo']]},
'Férias e ausências':{key:'vacations',title:'Planeje as pausas.',desc:'Férias e ausências com visibilidade sobre a cobertura da equipe.',add:'Registrar período',fields:[['person','Colaborador','person',true],['kind','Tipo',['Férias','Ausência'],true],['start','Início','date',true],['end','Fim','date',true],['notes','Observações','textarea']],columns:[['person','Colaborador'],['kind','Tipo'],['start','Início'],['end','Fim']]},
'Avaliações e feedbacks':{key:'reviews',title:'Desenvolver é acompanhar.',desc:'Registre fatos, reconheça avanços e acompanhe a evolução.',add:'Registrar avaliação',fields:[['person','Colaborador','person',true],['date','Data','date',true],['kind','Ocorrência',['Feedback positivo','Feedback negativo','Refugo','Retrabalho','Produtividade acima da meta','Produtividade abaixo da meta','Medida disciplinar'],true],['delta','Variação da nota','number',true],['notes','Descrição e contexto','textarea',true]],columns:[['person','Colaborador'],['date','Data'],['kind','Ocorrência'],['delta','Variação']]},
'Máquinas e equipamentos':{key:'machines',title:'Estrutura que faz acontecer.',desc:'Organize os equipamentos e os recursos da sua operação.',add:'Incluir máquina',fields:[['name','Identificação da máquina','text',true],['type','Tipo de máquina','text',true],['date','Aquisição','date',true],['area','Área',areas,true],['cost','Centro de custo','text',true],['status','Situação',['Em operação','Planejada','Inativa'],true],['shifts','Turnos de utilização','shifts',true],['benches','Bancadas','number'],['microscopes','Microscópios','number'],['instruments','Instrumentos de medição','number'],['exhaust','Sistemas de exaustão','number'],['notes','Observações','textarea']],columns:[['name','Máquina'],['type','Tipo'],['area','Área'],['cost','Centro de custo'],['status','Situação']]},
'Áreas de apoio':{key:'support',title:'Apoio para crescer.',desc:'Dimensione cada área a partir de critérios explícitos e máquinas vinculadas.',add:'Adicionar planejamento',fields:[['area','Área de apoio',areas,true],['shift','Turno',shifts,true],['current','Quadro atual','number',true],['needed','Quadro necessário','number',true],['machine','Máquina vinculada','machine',true],['notes','Critério e justificativa','textarea',true]],columns:[['area','Área de apoio'],['shift','Turno'],['current','Atual'],['needed','Necessário'],['machine','Máquina vinculada']]}
};
const names=['Colaboradores','Férias e ausências','Avaliações e feedbacks','Máquinas e equipamentos','Dimensionamento de equipe','Áreas de apoio','Indicadores','Histórico de alterações'];
const main=$('#menuView');
const functionsView=document.createElement('div');functionsView.id='functionsView';functionsView.className='app';functionsView.hidden=true;
const header=main.querySelector('header').cloneNode(true);header.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));header.querySelectorAll('button').forEach(b=>b.remove());functionsView.append(header);
const content=document.createElement('main');content.id='workspace';functionsView.append(content);main.after(functionsView);
document.body.insertAdjacentHTML('beforeend','<div id="notice" role="status"></div><dialog id="editor"><form id="recordForm"><div class="editor-head"><div><small id="editorKicker">CADASTRO</small><h2 id="editorTitle"></h2></div><button type="button" class="quiet" id="closeEditor" aria-label="Fechar">✕</button></div><div id="formFields" class="form-grid"></div><p id="formError" role="alert"></p><footer class="editor-footer"><button type="button" class="quiet" id="cancelEditor">Cancelar</button><button type="submit" class="solid">Salvar registro →</button></footer></form></dialog><dialog id="confirmDelete"><h2>Excluir este registro?</h2><p>A exclusão será registrada no histórico desta demonstração.</p><div class="editor-footer"><button class="quiet" id="keepRecord">Cancelar</button><button class="solid danger" id="deleteRecord">Excluir</button></div></dialog>');
const work=$('#workspace'),editor=$('#editor');let editing=null,editingType=null;
$('#closeEditor').onclick=$('#cancelEditor').onclick=()=>editor.close();$('#keepRecord').onclick=()=>$('#confirmDelete').close();
function home(){functionsView.hidden=true;$('#collaboratorsView').hidden=true;main.hidden=false;document.querySelectorAll('[data-open]').forEach(b=>b.classList.remove('current'));}
function open(n){if(n==='Colaboradores'){functionsView.hidden=true;syncPeople();window.showOrthoCollaborators();return;}page=n;query='';filter='';pageNo=1;main.hidden=true;$('#collaboratorsView').hidden=true;functionsView.hidden=false;work.hidden=false;render();document.querySelectorAll('[data-open]').forEach(b=>b.classList.toggle('current',b.dataset.open===n));$('#nextScreen').scrollTop=0;work.querySelector('h1')?.focus({preventScroll:true});}
document.querySelectorAll('[data-module]').forEach(b=>{const c=b.cloneNode(true);b.replaceWith(c);c.onclick=()=>open(c.dataset.module);});
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open));
document.querySelectorAll('[data-section]').forEach(b=>b.addEventListener('click',home));$('#logout').addEventListener('click',()=>{functionsView.hidden=true;$('#collaboratorsView').hidden=true;});
function metric(label,value,note=''){return `<div class="metric"><small>${label}</small><strong>${value}</strong><span>${note}</span></div>`;}
function badge(t){return `<span class="pill">${esc(t)}</span>`;}
function value(r,k){if(k==='person')return esc(personName(r[k]));if(k==='machine')return esc(db.machines.find(m=>m.id===r[k])?.name||'—');if(['date','start','end'].includes(k))return fmt(r[k]);if(k==='delta')return badge((Number(r[k])>0?'+':'')+r[k]);if(['status','shift'].includes(k))return badge(r[k]);return esc(r[k]??'—');}
function table(columns,rows,actions=false){return `<div class="table-scroll"><table><thead><tr>${columns.map(c=>`<th>${esc(c[1])}</th>`).join('')}${actions?'<th>Ações</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(c=>`<td>${value(r,c[0])}</td>`).join('')}${actions?`<td class="row-actions">${page==='Colaboradores'?`<button data-profile="${r.id}">Perfil</button>`:''}<button data-edit="${r.id}">Editar</button><button data-delete="${r.id}" aria-label="Excluir registro">×</button></td>`:''}</tr>`).join('')}</tbody></table></div>`;}
function empty(text='Tudo pronto para começar.'){return `<div class="empty-state"><div class="empty-mark">＋</div><h3>${text}</h3><p>Os registros aparecerão aqui conforme você cadastrar.</p></div>`;}
function rowsFor(c){return db[c.key].filter(r=>(!filter||r.area===filter||person(r.person)?.area===filter)&&(!query||[...Object.values(r),r.person?personName(r.person):''].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase())));}
let exportRows=[];
function render(){const c=configs[page];work.innerHTML=`<div class="work-heading"><div><button class="back-link" id="home">← Menu principal</button><h1 tabindex="-1">${c?.title||page}</h1><p>${c?.desc||'Uma visão conectada para decisões mais claras.'}</p></div>${c?`<button class="solid" id="add">＋ ${c.add}</button>`:''}</div><div class="demo-strip">Prévia interativa · Os registros ficam apenas nesta sessão. <button id="backup">Baixar cópia dos dados</button></div><div id="pageBody"></div>`;$('#home').onclick=home;$('#backup').onclick=()=>download('NeoOrtho_dados.json',JSON.stringify(db,null,2),'application/json');if(c){$('#add').onclick=()=>edit(c.key);renderList(c);}else if(page==='Dimensionamento de equipe')renderSizing();else if(page==='Indicadores')renderBI();else renderAudit();}
function renderList(c){const all=rowsFor(c);exportRows=all.map(r=>Object.fromEntries(c.columns.map(([k,l])=>[l,k==='person'?personName(r[k]):k==='machine'?db.machines.find(m=>m.id===r[k])?.name:r[k]])));const shown=all.slice((pageNo-1)*10,pageNo*10);let stats='';if(c.key==='people')stats=metric('Colaboradores',db.people.length)+metric('Em atividade',db.people.filter(p=>active(p)).length)+metric('Áreas',new Set(db.people.map(p=>p.area)).size);if(c.key==='machines')stats=metric('Equipamentos',db.machines.length)+metric('Em operação',db.machines.filter(m=>m.status==='Em operação').length)+metric('Planejados',db.machines.filter(m=>m.status==='Planejada').length);if(c.key==='reviews')stats=metric('Registros',db.reviews.length)+metric('Avaliados',new Set(db.reviews.map(r=>r.person)).size)+metric('Escala','0–10','Início em 10 · pesos definidos no registro');if(c.key==='vacations')stats=metric('Períodos',db.vacations.length)+metric('Ausentes hoje',new Set(db.vacations.filter(v=>v.start<=today()&&v.end>=today()).map(v=>v.person)).size)+metric('Próximos períodos',db.vacations.filter(v=>v.start>today()).length);if(c.key==='support')stats=metric('Planejamentos',db.support.length)+metric('Quadro atual',db.support.reduce((n,r)=>n+Number(r.current),0))+metric('Necessidade adicional',db.support.reduce((n,r)=>n+Math.max(0,r.needed-r.current),0));
$('#pageBody').innerHTML=`<div class="metrics">${stats}</div>${c.key==='reviews'?'<p class="context-note">Pesos provisórios: positivos +0,5; negativos −0,5; refugo −0,5; retrabalho −1. Ajustáveis em cada registro. Notas apoiam a análise humana; não geram decisões automáticas.</p>':''}<div class="records"><div class="toolbar"><input id="searchRecords" aria-label="Pesquisar registros" placeholder="Pesquisar…" value="${esc(query)}"><select id="areaFilter" aria-label="Filtrar área"><option value="">Todas as áreas</option>${areas.map(a=>`<option ${filter===a?'selected':''}>${a}</option>`).join('')}</select><button class="quiet" id="export">Exportar CSV ↗</button></div>${shown.length?table(c.columns,shown,true):empty(all.length?'Nenhum resultado.':'Seu próximo registro começa aqui.')}<div class="pagination"><span>${all.length} registro(s)</span><button id="prev" ${pageNo===1?'disabled':''}>←</button><span>${pageNo} / ${Math.max(1,Math.ceil(all.length/10))}</span><button id="next" ${pageNo*10>=all.length?'disabled':''}>→</button></div></div><div id="extra"></div>`;
$('#searchRecords').oninput=e=>{query=e.target.value;pageNo=1;const pos=e.target.selectionStart;renderList(c);$('#searchRecords').focus();$('#searchRecords').setSelectionRange(pos,pos);};$('#areaFilter').onchange=e=>{filter=e.target.value;pageNo=1;renderList(c)};$('#export').onclick=()=>csv(exportRows);$('#prev').onclick=()=>{pageNo--;renderList(c)};$('#next').onclick=()=>{pageNo++;renderList(c)};
work.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(c.key,b.dataset.edit));work.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(c.key,b.dataset.delete));work.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>profile(b.dataset.profile));if(c.key==='vacations')vacationExtra();}
function field(f,r){const[k,label,type,req]=f,val=r[k]??'',attr=`name="${k}" id="field-${k}" ${req?'required':''}`;let el;if(type==='textarea')el=`<textarea ${attr} rows="3">${esc(val)}</textarea>`;else if(type==='shifts')el=shifts.map(t=>`<label class="check"><input type="checkbox" name="shifts" value="${t}" ${(r.shifts||shifts).includes(t)?'checked':''}>${t}</label>`).join('');else if(Array.isArray(type)||['person','machine'].includes(type)){const opts=type==='person'?db.people.map(p=>[p.id,p.name+' · '+p.registration]):type==='machine'?db.machines.filter(m=>m.status!=='Inativa').map(m=>[m.id,m.name]):type.map(x=>[x,x]);el=`<select ${attr}><option value="">Selecione</option>${opts.map(([id,n])=>`<option value="${esc(id)}" ${val===id?'selected':''}>${esc(n)}</option>`).join('')}</select>`;}else el=`<input ${attr} type="${type}" value="${esc(val)}" ${type==='number'?`step="${k==='delta'?'0.5':'1'}" min="${k==='delta'?'-10':'0'}" ${k==='delta'?'max="10"':''}`:''}>`;return `<div class="field ${type==='textarea'?'wide':''}"><label for="field-${k}">${label}${req?' *':''}</label>${el}</div>`;}
function edit(key,id){const c=Object.values(configs).find(c=>c.key===key);if(['reviews','vacations'].includes(key)&&!db.people.length)return toast('Cadastre um colaborador primeiro.');if(key==='support'&&!db.machines.some(m=>m.status!=='Inativa'))return toast('Cadastre uma máquina ativa ou planejada primeiro.');editing=id;editingType=key;const r=db[key].find(r=>r.id===id)||{date:today(),delta:0.5,status:'Em operação'};$('#editorTitle').textContent=id?'Editar registro':c.add;$('#editorKicker').textContent=Object.keys(configs).find(k=>configs[k]===c);$('#formFields').innerHTML=c.fields.map(f=>field(f,r)).join('');$('#formError').textContent='';editor.showModal();if(key==='reviews')$('#field-kind').onchange=e=>{$('#field-delta').value={'Feedback positivo':.5,'Feedback negativo':-.5,'Refugo':-.5,'Retrabalho':-1,'Produtividade acima da meta':.5,'Produtividade abaixo da meta':-.5,'Medida disciplinar':0}[e.target.value]??0;};}
$('#recordForm').onsubmit=e=>{e.preventDefault();const key=editingType,c=Object.values(configs).find(c=>c.key===key),form=new FormData(e.target),r=Object.fromEntries(form);r.id=editing||uuid();for(const[k,,t]of c.fields){if(t==='number')r[k]=Number(r[k]||0);else if(typeof r[k]==='string')r[k]=r[k].trim();}const fail=m=>{$('#formError').textContent=m;};if(c.fields.some(([k,,t,req])=>req&&t!=='number'&&t!=='shifts'&&!r[k]))return fail('Preencha os campos obrigatórios.');if(r.start&&r.end&&r.end<r.start)return fail('A data final precisa ser igual ou posterior ao início.');if(key==='people'){if(db.people.some(p=>p.id!==r.id&&p.registration.toLowerCase()===r.registration.toLowerCase()))return fail('Esta matrícula já está cadastrada.');if(r.birth&&r.birth>today())return fail('Nascimento não pode estar no futuro.');if(r.birth&&r.start<r.birth)return fail('A entrada deve ser posterior ao nascimento.');}if(key==='machines'){r.shifts=form.getAll('shifts');if(!r.shifts.length)return fail('Selecione pelo menos um turno.');if(db.machines.some(m=>m.id!==r.id&&m.name.toLowerCase()===r.name.toLowerCase()))return fail('Identificação de máquina já cadastrada.');}if(key==='vacations'){if(db.vacations.some(v=>v.id!==r.id&&v.person===r.person&&overlap(v,r)))return fail('Já existe um período sobreposto para este colaborador.');const p=person(r.person);if((p.start&&r.start<p.start)||(p.end&&r.end>=p.end))return fail('O período precisa estar dentro do vínculo do colaborador.');}if(key==='reviews'){r.created=db.reviews.find(x=>x.id===r.id)?.created||new Date().toISOString();if(!Number.isFinite(r.delta)||r.delta< -10||r.delta>10)return fail('Variação deve estar entre -10 e 10.');if(/positivo|acima/.test(r.kind)&&r.delta<0)return fail('Uma ocorrência positiva não deve reduzir a nota.');if(/negativo|abaixo|Refugo|Retrabalho/.test(r.kind)&&r.delta>0)return fail('Esta ocorrência não deve aumentar a nota.');}const old=db[key].find(x=>x.id===r.id);if(old)db[key]=db[key].map(x=>x.id===r.id?r:x);else db[key].push(r);audit(old?'Alteração':'Inclusão',page,old||null,r);editor.close();syncPeople();if(functionsView.hidden){window.showOrthoCollaborators();}else render();toast('Registro salvo nesta sessão.');};
function remove(key,id){if(key==='people'&&[...db.vacations,...db.reviews].some(r=>r.person===id))return toast('Há férias ou avaliações vinculadas. Registre a data de saída ou remova os vínculos antes.');if(key==='machines'&&db.support.some(r=>r.machine===id))return toast('Há planejamentos vinculados a esta máquina. Atualize-os antes de excluir.');$('#confirmDelete').showModal();$('#deleteRecord').onclick=()=>{const old=db[key].find(r=>r.id===id);db[key]=db[key].filter(r=>r.id!==id);audit('Exclusão',page,old,null);$('#confirmDelete').close();pageNo=1;syncPeople();if(functionsView.hidden)window.showOrthoCollaborators();else render();toast('Registro excluído.');};}
function profile(id){const p=person(id);const d=$('#moduleDialog');d.innerHTML=`<h2>${esc(p.name)}</h2><p>${esc(p.registration)} · ${esc(p.role)}</p><div class="profile-score">${score(id).toLocaleString('pt-BR')}<small>/ 10</small></div><p>${esc(p.area)} · ${esc(p.shift)}</p><p>Entrada: ${fmt(p.start)} · Saída: ${fmt(p.end)}<br>Nascimento: ${fmt(p.birth)}<br>Centro de custo: ${esc(p.cost)}</p><p>${esc(p.notes)}</p><button class="quiet" id="removePerson">Excluir colaborador</button><h3>Histórico de acompanhamento</h3>${db.reviews.filter(r=>r.person===id).map(r=>`<p><b>${esc(r.kind)}</b> · ${fmt(r.date)} (${r.delta>0?'+':''}${r.delta})<br>${esc(r.notes)}</p>`).join('')||'<p>Nenhuma ocorrência registrada.</p>'}<form method="dialog"><button class="quiet">Fechar</button></form>`;d.showModal();$('#removePerson').onclick=()=>{d.close();remove('people',id);};}
function staffing(date=today(),future=false){const keys=new Set();db.machines.filter(m=>m.status==='Em operação'||future&&m.status==='Planejada').forEach(m=>m.shifts.forEach(t=>keys.add(m.area+'|'+t)));db.people.filter(p=>active(p,date)&&/^Operador/i.test(p.role)).forEach(p=>keys.add(p.area+'|'+p.shift));return [...keys].sort().map(key=>{const[area,shift]=key.split('|'),machines=db.machines.filter(m=>m.area===area&&m.shifts.includes(shift)&&(m.status==='Em operação'||future&&m.status==='Planejada')),team=db.people.filter(p=>active(p,date)&&p.area===area&&p.shift===shift&&/^Operador/i.test(p.role)),absent=team.filter(p=>db.vacations.some(v=>v.person===p.id&&v.start<=date&&v.end>=date)).length,needed=Math.ceil(machines.length/3);return {area,shift,machines:machines.length,needed,current:team.length,absent,available:team.length-absent,balance:team.length-absent-needed,linked:machines.filter(m=>m.status==='Planejada').map(m=>m.name).join(', ')};});}
function vacationExtra(){const conflicts=[];db.vacations.forEach((a,i)=>db.vacations.slice(i+1).forEach(b=>{const x=person(a.person),y=person(b.person);if(x&&y&&x.area===y.area&&x.shift===y.shift&&overlap(a,b))conflicts.push(`${x.name} e ${y.name} · ${x.area}, ${x.shift} · ${fmt(a.start>b.start?a.start:b.start)} a ${fmt(a.end<b.end?a.end:b.end)}`);}));$('#extra').innerHTML=`<section class="insight"><h3>Sobreposições da equipe</h3>${conflicts.length?conflicts.map(t=>`<p class="warning">${esc(t)}</p>`).join(''):'<p>Nenhuma sobreposição entre colaboradores da mesma área e turno.</p>'}<label>Ver cobertura em <input type="date" id="coverageDate" value="${today()}"></label><div id="coverage"></div></section>`;const draw=()=>{const date=$('#coverageDate').value;if(!date)return;const map=new Map;db.people.filter(p=>active(p,date)).forEach(p=>{const k=p.area+'|'+p.shift;if(!map.has(k))map.set(k,{area:p.area,shift:p.shift,total:0,absent:0});const r=map.get(k);r.total++;if(db.vacations.some(v=>v.person===p.id&&v.start<=date&&v.end>=date))r.absent++;});$('#coverage').innerHTML=table([['area','Área'],['shift','Turno'],['total','Equipe'],['absent','Ausentes'],['available','Disponíveis']],[...map.values()].map(r=>({...r,available:r.total-r.absent})));};$('#coverageDate').onchange=draw;draw();}
function renderSizing(){ $('#pageBody').innerHTML='<div class="insight"><h3>Planejamento de operadores</h3><p>1 operador por turno para cada 3 máquinas, arredondado para cima por área. Ausências consideradas na data selecionada.</p><div class="toolbar"><input type="date" id="sizingDate" value="'+today()+'" aria-label="Data do planejamento"><label class="check"><input id="future" type="checkbox"> Incluir máquinas planejadas</label><button class="quiet" id="exportSizing">Exportar CSV ↗</button></div></div><div id="sizingResult"></div>';const draw=()=>{const date=$('#sizingDate').value;if(!date)return;const rows=staffing(date,$('#future').checked);$('#sizingResult').innerHTML=`<div class="metrics">${metric('Operadores necessários',rows.reduce((n,r)=>n+r.needed,0))}${metric('Disponíveis',rows.reduce((n,r)=>n+r.available,0))}${metric('Déficit por área/turno',rows.reduce((n,r)=>n+Math.max(0,-r.balance),0))}</div>${rows.length?table([['area','Área'],['shift','Turno'],['machines','Máquinas'],['needed','Necessários'],['available','Disponíveis'],['balance','Saldo'],['linked','Aquisições planejadas']],rows):empty()}<section class="insight"><h3>Pontos de atenção</h3>${rows.filter(r=>r.balance<0).map(r=>`<p class="warning">${esc(r.area)} · ${r.shift}: faltam ${-r.balance} operador(es). ${r.linked?'Aquisição vinculada: '+esc(r.linked)+'.':'Sem aquisição planejada vinculada; avaliar cobertura e balanceamento.'}</p>`).join('')||'<p>Nenhum déficit calculado.</p>'}<p>Áreas de apoio possuem critérios próprios no planejamento de apoio.</p></section>`;$('#exportSizing').onclick=()=>csv(rows);};$('#sizingDate').onchange=$('#future').onchange=draw;draw();}
function bars(title,rows){const max=Math.max(1,...rows.map(r=>r[1]));return `<section class="insight"><h3>${title}</h3>${rows.length?rows.map(([label,n])=>`<div class="bar-row"><span>${esc(label)}</span><div><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`).join(''):'<p>Cadastre colaboradores para visualizar a distribuição.</p>'}</section>`;}
function renderBI(){const people=db.people.filter(p=>active(p)),count=k=>[...new Set(people.map(p=>p[k]))].map(v=>[v,people.filter(p=>p[k]===v).length]),rows=staffing();$('#pageBody').innerHTML=`<div class="metrics">${metric('Pessoas em atividade',people.length)}${metric('Máquinas em operação',db.machines.filter(m=>m.status==='Em operação').length)}${metric('Ausentes hoje',people.filter(p=>db.vacations.some(v=>v.person===p.id&&v.start<=today()&&v.end>=today())).length)}</div><div class="bi-grid">${bars('Equipe por turno',count('shift'))}${bars('Estrutura por cargo',count('role'))}${bars('Distribuição por área',count('area'))}<section class="insight"><h3>Balanceamento de operadores</h3>${rows.filter(r=>r.balance<0).map(r=>{const sources=rows.filter(x=>x.area===r.area&&x.balance>0);return `<p>${esc(r.area)} · ${r.shift}: déficit de ${-r.balance}.${sources.length?' Avaliar remanejamento: '+sources.map(x=>x.shift+' com saldo '+x.balance).join(', ')+'.':' Sem excedente na mesma área.'}</p>`}).join('')||'<p>Sem desequilíbrio calculado no momento.</p>'}<small>Sugestões dependem de disponibilidade e qualificação; nenhuma transferência é automática.</small></section></div><section class="insight"><h3>Próximas férias</h3>${db.vacations.filter(v=>v.kind==='Férias'&&v.end>=today()).sort((a,b)=>a.start.localeCompare(b.start)).slice(0,8).map(v=>`<p>${esc(personName(v.person))} <span class="pill">${fmt(v.start)} → ${fmt(v.end)}</span></p>`).join('')||'<p>Nenhum período programado.</p>'}</section>`;}
function renderAudit(){const rows=db.audit;$('#pageBody').innerHTML=`<div class="insight"><h3>Trilha da demonstração</h3><p>Registro local de alterações com antes e depois. O responsável U135613 é simulado; esta versão ainda não possui auditoria autenticada.</p><button id="exportAudit" class="quiet">Exportar histórico ↗</button></div><div class="audit-list">${rows.map(r=>`<details><summary><span>${esc(r.action)} · ${esc(r.type)}</span><small>${new Date(r.date).toLocaleString('pt-BR')} · ${esc(r.user)}</small></summary><div class="audit-detail"><div><b>Antes</b><pre>${esc(JSON.stringify(r.before,null,2))}</pre></div><div><b>Depois</b><pre>${esc(JSON.stringify(r.after,null,2))}</pre></div></div></details>`).join('')||empty('O histórico começa com a primeira alteração.')}</div>`;$('#exportAudit').onclick=()=>download('NeoOrtho_historico.json',JSON.stringify(rows,null,2),'application/json');}
// Exposto apenas para verificação local das regras, sem serviços externos.
window.NeoOrthoDemo={staffing,score,overlap};
})();
